### ISSUE TITLE
请教下，配置文件的位置

### ISSUE THREAD

**Issue by Yaob1990** [DarkHighness/quickjet#1]
`C:\Users\admin\AppData\Local\JetBrains\WebStorm2020.1`

我在这个目录下面找不到`recentProjectDirectories.xml`或者`recentProjects.xml`,求指点下

**Comment by DarkHighness** [comment]
当前版本的文件路径应该为`C:\Users\admin\AppData\Romaing\JetBrains\WebStorm2020.1`下
目前还没有更新插件做兼容

**Comment by Yaob1990** [comment]
感谢~，找到了
